chore/update acapy 0.8.2
Indicio-tech/aries-acapy-plugin-data-transfer pull request #6
Opened 2023-06-09 17:41 UTC by anwalker293

Using new release candidate!

2023-07-07 19:37 UTC, dbluhm requested changes

2023-07-07 19:37 UTC, dbluhm commented on pyproject.toml
> +aries-cloudagent = { version = "0.8.2-rc0", allow-prereleases = true }
Let's use the full release!

2023-07-18 17:30 UTC, anwalker293 commented
@dbluhm Fixed + passed tests! :)

2023-07-18 17:31 UTC, dbluhm approved these changes

2023-07-18 17:31 UTC, merged